# Generated by Django 4.2 on 2023-06-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ombor',
            old_name='uesr',
            new_name='user',
        ),
    ]
